def servir_agua_hervida ():
	print('Tomar el hervidor y ponerle agua')
	print('Encender el hervidor para hervir el agua')
	print('Una vez hervida el agua servirla')

#Servir_bebidas_calientes
print('================================')
print('Hacer y servir café')
print('================================')
print('Tomar una taza')
print('Tomar una cuchara')
print('Buscar el café')
print('Buscar el endulzante')
print('Poner café en la taza')
print('Poner endulzante en la taza')
servir_agua_hervida()
print(' en la taza')
print('Revolver contenido')
print('Disfrutar del café')
print('================================')
print('Hacer y servir mate')
print('================================')
print('Tomar una matero')
print('Tomar una cuchara')
print('Buscar el mate')
print('Buscar el endulzante')
print('Poner mate en el matero')
print('Poner endulzante en el matero')
servir_agua_hervida()
print(' en el matero')
print('Revolver contenido o reposar')
print('Disfrutar del mate')
#FinAlgoritmo
